kind: pipeline
type: docker
name: default

steps:
#  - name: greeting
#    image: golang:1.18
#    commands:
#      - go mod tidy
#      - go test

  - name: publish
    image: plugins/docker
    settings:
      repo: dapmoed/dron-ci-test
      tags:
        - latest
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to: 91972279

trigger:
  branch:
    - main