kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: golang:1.18
    commands:
      - go mod tidy
      - go test

  - name: publish
    image: plugins/docker
    settings:
      environment:
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
      username: $USERNAME
      password: $PASSWORD
      repo: dapmoed/dron-ci-test
      tags:
        - latest
    commands:
      - echo "You can call the secrets like this examples below."
      - echo $USERNAME
      - echo $PASSWORD
      - echo "In both cases, and for security reasons, you wi

trigger:
  branch:
    - main