kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: golang:1.18
    commands:
      - go mod tidy
      - go test

  - name: publish
    image: plugins/docker
    settings:
      environment:
        DOCKER_USERNAME:
          from_secret: docker_username
        DOCKER_PASSWORD:
          from_secret: docker_password
      username: $DOCKER_USERNAME
      password: $DOCKER_PASSWORD
      repo: dapmoed/dron-ci-test
      tags:
        - latest

trigger:
  branch:
    - main