kind: pipeline
type: docker
name: default

steps:
#  - name: tests
#    image: golang:1.18
#    commands:
#      - go mod tidy
#      - go test
#
#  - name: publish
#    image: plugins/docker
#    settings:
#      repo: dapmoed/dron-ci-test
#      tags:
#        - latest
#      username:
#        from_secret: docker_username
#      password:
#        from_secret: docker_password

  - name: Syntax Check
    image: plugins/ansible
    settings:
      become: true
      playbook: ansible/playbook.yaml
      inventory: inventory
      private_key:
        from_secret: drone_ssh_private_key
      ssh_extra_args: "-o StrictHostKeyChecking=no"
      syntax_check: true

  - name: deploy
    image: plugins/ansible:3
    settings:
      playbook: ansible/playbook.yaml
      inventory: ansible/inventory
      syntax_check: true

  - name: notify
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: tg_token
      to: -1001731607931

trigger:
  branch:
    - main