kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: golang:1.18
    commands:
      - go build
      - go test

  - name: publish
    image: plugins/docker
    settings:
      username: ${DOCKER_USERNAME}
      password: ${DOCKER_PASSWORD}
      repo: dapmoed/dron-ci-test
      tags:
        - latest

trigger:
  branch:
    - main